version: "3.8"
services:
  backend:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydb
    volumes:
      - ./.env:/app/.env
    depends_on:
      - db

  frontend:
    container_name: spa
    build:
      context: ./spa
      dockerfile: Dockerfile
    ports:
      - "80:80"

  db:
    image: postgres:17.2
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5434:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
